### ISSUE TITLE
Variable in serialisation

### ISSUE THREAD

**Issue by ClementBrohon** [universAAL/nativeandroid#4] opened 2017-05-23 09:36 UTC
Hello

Can you explain what this line do please?

` "&var2;100&var2;"^^xsd:int`

I noticed that 
- the var2 is the key of a input
- it begins with the character "&" and ends with ";" 
- Two tag "&var2;" circle a number, and the type is defined with "^^xsd:int"

I suppose that this line will be remplaced by a value. This value is the key (URI?) or the value of my var? Why I circle a number if I send it with the value of var2? Is it the default value?

And I don't understand why the timestamp has this value:

`ctxt:hasTimestamp "1384864157846"^^xsd:long ;`

This line come from the lighting exemple and the complete serialization is:

```
<advertisement>
            <title>Publish light source brightness</title>
            <description>CONTEXT PUBLISHER EVENT: Publish changes in brightness of a light source.</description>
            <action>org.universaal.nativeandroid.light.EVENT_LIGHTCHANGE</action>
            <category>android.intent.category.DEFAULT</category>
            <input>
                <key>var1</key>
                <value>lamp</value>
            </input>
            <input>
                <key>var2</key>
                <value>brightness</value>
            </input>
            <serialization>
               <![CDATA[
               @prefix ph: <http://ontology.universaal.org/PhThing.owl#> .
               @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
               @prefix tst: <http://ontology.igd.fhg.de/LightingServer.owl#> .
               @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
               @prefix light: <http://ontology.universaal.org/Lighting.owl#> .
               @prefix ctxt: <http://ontology.universAAL.org/Context.owl#> .
               @prefix owl: <http://www.w3.org/2002/07/owl#> .

               <urn:org.universAAL.middleware.context.rdf:ContextEvent#_:c043cf9e99c148f8:be9> ctxt:hasProvider tst:LightServer ;
                 a ctxt:ContextEvent ;
                 rdf:subject tst:&var1;controlledLamp1&var1; ;
                 ctxt:hasTimestamp "1384864157846"^^xsd:long ;
                 rdf:predicate light:srcBrightness ;
                 rdf:object "&var2;100&var2;"^^xsd:int .

               tst:&var1;controlledLamp1&var1; a light:LightSource ,
                   ph:Device ,
                   ph:PhysicalThing ;
                 light:srcBrightness "&var2;100&var2;"^^xsd:int .

               ctxt:gauge a ctxt:ContextProviderType .

               tst:LightServer a ctxt:ContextProvider ;
                 ctxt:hasType ctxt:gauge ;
                 ctxt:myClassesOfEvents [
                     a ctxt:ContextEventPattern ;
                     <http://www.w3.org/2000/01/rdf-schema#subClassOf> [
                         a owl:Restriction ;
                         owl:allValuesFrom light:LightSource ;
                         owl:onProperty rdf:subject
                       ]
                   ] .
               ]]>
            </serialization>
         </advertisement>

```

**Comment by Alfiva** [comment] 2017-05-23 13:41
I know it's a bit messy, let me clarify:
-In the **XML** you define **key-value pairs**. Example: **key**: var1, **value**: lamp)
-In the Android Broadcast **Intent** you send to send the associate Event, you put an **Intent Extra** with a key equal to the previous "value", and a value with an actual value (I know, confusing). Example: **Extra key**: lamp, **Extra value**: whatever
-Then the Event built by uAAL will be the one you defined in the XML, but replacing the content between &var1; and &var1; with the content you passed in the Intent extra. Example: **"&var1;100&var1;"^^xsd:int** will become **"whatever"^^xsd:int**
Of course this will fail because instead of **whatever** it should have been a numeric value compatible with xsd:int. Example: **Extra value**: 50

**Comment by ClementBrohon** [comment] 2017-05-23 14:36
And why there are 100 (Is it a specific number?) between the two &var2? Is it the default value if I forgot to put a extra value?

**Comment by Alfiva** [comment] 2017-05-23 14:39
It's like the "default" value of the "template", it ought to be replaced by your new value in the intent extra no matter what (in other words, do not forget to put the extra value)

**Comment by amedranogil** [comment] 2017-05-24 08:27
Is the timestamp automatically set? or should @ArveduiLuminas  configure it also as a variable is we want to porsess events by timestamp?

**Comment by Alfiva** [comment] 2017-05-24 08:33
timestamp and context event URI are automatically set with the current time and new random ID respectively.
No need to replace them manually. In fact, if you replace them manually they will be ignored.

**Comment by ClementBrohon** [comment] 2017-05-25 09:48
I try to create my own service callee.

I don't understand this line:
`ns:has_process ns1:turnOnProcess `

I search throughout the program and I see only one occurence of this "turnOnProcess", this one. And there is no reference in the caller. I can't see what is the "turnOnProcess" because the url of the lighting ontology is not available, so I can adapt this code. What is the aim of this line?



It is from:

```
<requirement>
                <title>Turn light source on</title>
                <description>SERVICE CALLER REQUEST: Turn on a specific light source.</description>
                <action>org.universaal.nativeandroid.light.CALL_ON</action>
                <category>android.intent.category.DEFAULT</category>
                <remote>true</remote>
                <input>
                    <key>var1</key>
                    <value>lamp</value>
                </input>
                <serialization>
                    <![CDATA[
                        @prefix owl: <http://www.w3.org/2002/07/owl#> .
                        @prefix ns: <http://ontology.universaal.org/PhThing.owl#> .
                        @prefix ns1: <http://ontology.igd.fhg.de/LightingServer.owl#> .
                        @prefix ns2: <http://ontology.universaal.org/Device.owl#> .
                        @prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .
                        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
                        @prefix ns3: <http://www.daml.org/services/owl-s/1.1/Process.owl#> .
                        @prefix : <http://ontology.universAAL.org/Service.owl#> .

                        _:BN000000
                            a pvn:ServiceRequest ;
                            pvn:requiredResult [
                                a ns3:Result ;
                                ns3:hasEffect [
                                    :affectedProperty [
                                        a :PropertyPath ;
                                        :thePath (
                                            ns2:hasValue
                                        )
                                    ] ;
                                    a :ChangeEffect ;
                                    :propertyValue "100"^^xsd:int
                                ]
                            ] ;
                            pvn:requestedService [
                                a ns2:LightActuator ;
                                pvn:instanceLevelRestrictions [
                                    owl:hasValue <http://ontology.igd.fhg.de/LightingServer.owl#&var1;controlledLamp0&var1;> ;
                                    a owl:Restriction ;
                                    owl:onProperty ns2:hasValue
                                ] ;
                                pvn:numberOfValueRestrictions "1"^^xsd:int
                            ] .


                        <http://ontology.igd.fhg.de/LightingServer.owl#&var1;controlledLamp0&var1;>
                            a ns2:LightActuator ,
                            ns:Device ,
                            ns:PhysicalThing .
                      ]]>
                </serialization>
            </requirement>
```

**Comment by Alfiva** [comment] 2017-05-25 10:35
You should not worry about this thing, there is nothing for you to do with it.
When creating service profiles with uAAL code, a xxxProcess is associated automatically to each service profile, for matchmaking purposes (attaching the word "Process" to your service profile URI).
You don't have to do anything about it. Just ignore it.
The only time you would have to deal with this would be if you are writing your serialized service profiles manually (I discourage this) or using an existing one as a template to make your own (a bit less discouraged). In this case, you have to make sure the name is: {myserviceprofileuri}Process

**Comment by ClementBrohon** [comment] 2017-05-25 11:04
I try to use a existing one as a template. I don't think I have an other choice. I see only this paragraph:

> A trick is to develop a universAAL OSGi-based application with the callers, publishers, etc, you want to include in your app and use its functional manifest as a starting point for the metadata file. However the metadata changes a bit the required content and adds some tags. Another alternative is coding that same mock-up OSGi application but use the MessageContentSerializerEx OSGi interface from mw.data.serialization to obtain the Turtle serializations you need.

But I haven't seen any documentation about this serializer, I am not sure to understand what is a "mock-up OSGi application". Maybe it's a "classical" application as described in the wiki "Universal/plateform/DG Developing with universAAL".

Maybe I have missed a wiki page about this?

**Comment by Alfiva** [comment] 2017-05-25 11:31
The serializations in uAAL.xml in Android are serializations of conventional uAAL data models: ContextEvents, ServiceRequests, and so on...
To have these in your own App's uAAL.xml, I discourage writing them manually from scratch (perhaps the most simple ones are doable, like ContextEvents).
Using an existing uAAL.xml from the examples and modify it to your needs is an option, but only if you want to do something similar (e.g. providing the same type of service) and if you really know what you are doing.
The other option, what I usually do, is create a regular uAAL application for OSGi, as explained in all of the platform documentation. I build the ContextEvent, or ServiceRequest, or whatever, and then use the serializer to print it out, and copy it into uAAL.xml.
**How to use the serializer**
In the Activator of the OSGi application:
```
    public static MessageContentSerializerEx parser;

    public void start(BundleContext bcontext) throws Exception {
	Activator.osgiContext = bcontext;
	Activator.context = uAALBundleContainer.THE_CONTAINER
		.registerModule(new Object[] { bcontext });
	String filter = "(objectclass="
		+ MessageContentSerializerEx.class.getName() + ")";
	ServiceReference[] references = bcontext.getServiceReferences((String)null, filter);
	if(references.length>0){
	    parser = (MessageContentSerializerEx)bcontext.getService(references[0]);
	    // Create the uAAL model you want, e.g. a ContextEvent
	    ContextEvent mymodel;
	    ...
	    // You can print it in the OSGi console, for instance
	    System.out.println(parser.serialize(mymodel));
	}
    }
```

**Comment by amedranogil** [comment] 2017-05-25 12:44
you can also use the new OntTestCase, which might be a bit simpler (specially to run: run as JUnit test, or just mvn install):
```Java
public class ContextTEST extends OntTestCase{

	public void testSerializeBusMember() {
                // Create the uAAL model you want, e.g. a ContextEvent
	        ContextEvent mymodel;
                //...

		//print it
                System.out.println(serialize(mymodel));
         }
}
```

**Comment by ClementBrohon** [comment] 2017-05-29 10:23
I use a small project to serialize my services, maybe I can share it here? 
(I can't import here. I don't understand why, because it's a zip)


You have just to unzip, import and Eclipse and write your code here:
![image](https://cloud.githubusercontent.com/assets/25262825/26546173/ee0c575e-4468-11e7-9e86-4aa415901256.png)

**Comment by ClementBrohon** [comment] 2017-06-12 09:46
I try to pass a value from a caller service to a callee service. 

My lamp can light up with an intensity between 0 and 100, I try to translate this value. The ontology allows me to associate with a lamp a value with LightActuaor.hasValue.

So I put the value in` :propertyValue "&var1;100&var1;"^^<http://www.w3.org/2001/XMLSchema#int>`

I would like to recover this value with my callee to adjust the brightness.

How do this?

I try a lot of thing with output/input but I think I don't follow the right line of thought.

Thanks you

**Comment by Alfiva** [comment] 2017-06-15 09:03
Are you talking about getting that value from a plain old java Service Callee (a.k.a. from an OSGi app) or getting it from the Android intent (in an Android app)?

-In the first case, when you create a Service Profile for setting the light value, you define that with .addInputValueFilter (or something like that, sorry, i don't remember the exact words now, check the auto-complete). When the ServiceRequest is built, the value is set with the equivalent method. Then in your handleCall() method of the ServiceCallee that gets the call, you get teh value with call.getInput(URI_YOU_GAVE_IT_IN_PROFILE). You have to cast it to the class that you know is being used (e.g. Integer).

-In Android though, when all is called and done you will get an Intent delievered to the broadcast receiver that you set for that call in the uAAL.xml. That Intent will have an Extra, its key is the one associated to "&var1". Just get it from the intent as explained here: https://github.com/universAAL/nativeandroid/wiki/Adapting-or-developing-your-app-for-uAAL#Writing_Code . IIRC it will be a String, so parse appropriately.

**Comment by Alfiva** [comment] 2017-06-15 09:05
Now I checked, that ServiceProfile method I mentioned is .addFilteringInput, not .addInputValueFilter. That .addInputValueFilter is the equivalent in the ServiceRequest

**Comment by ClementBrohon** [comment] 2017-06-21 15:06
I wasn't clear I think.

I have two applications, one receiver (with a callee service) and one emitter (with a caller service) and to make the link an ontology (device).

I just want to throw as instruction:
Thread: LampActuator
Predicate: HasValue
Object: An integer between 0 and 100, no matter which one.

I set up two instructions in my serializer.

```
ServiceRequest req = new ServiceRequest("http://clement.concept.org/#request_light", new DeviceService(), null);
		req.addValueFilter(new String[]{LightActuator.PROP_HAS_VALUE }, 100);
		req.addChangeEffect(new String[]{LightActuator.PROP_HAS_VALUE }, new Integer(0));

System.out.println(serialize(req));
```

```
DeviceService profile1 = new DeviceService("http://clement.concept.org/#device_service_watch_light_change");
    	profile1.addFilteringInput("http://clement.concept.org#var1", "http://www.w3.org/2001/XMLSchema#int" , 1, 1, new String[]{LightActuator.PROP_HAS_VALUE });
    	profile1.getProfile().addChangeEffect(new String[]{LightActuator.PROP_HAS_VALUE }, new Integer(0));
    	profs[0]=profile1.getProfile();

System.out.println(serialize(profile1.getProfile()));
```

For my tests, I keep this value of 0 for serviceProfile and change the 0 for serviceRequest to & var1. I get a logical result, meaning that the match between the two service is only done if my & var1 equals 0. My idea was then to change in the profile service the 0 of the object by & var2 of To be able to retrieve it as input. It did not work, the service caller and calee never match again.

I found and adapted a tip of program that allows me to make the extra list in an intent. I only find one named "proxy".

My question is how to set my profile service to accept a non-fixed value in the object, and then how to recover it? I do not find any value nor var1, nor the valuevar1 in the extra of my intent, just proxy.


I am not absolutely at ease with the <intput> tags I may have made a mistake in their use. I put my service callee

```
<requirement>
                <title>Turn light source on</title>
                <description>SERVICE CALLER REQUEST: Turn on a specific light source.</description>
                <action>org.universaal.nativeandroid.forcerUAAL.PUT_ON</action>
                <category>android.intent.category.DEFAULT</category>
                <input>
                    <key>Allume</key>
                    <value>Allume_lamp</value>
                </input>
                <serialization>
                    <![CDATA[
                        @prefix owl: <http://www.w3.org/2002/07/owl#> .
                        @prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .
                        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
                        @prefix ns: <http://www.daml.org/services/owl-s/1.1/Process.owl#> .
                        @prefix ns1: <http://ontology.universAAL.org/Device.owl#> .
                        @prefix : <http://ontology.universAAL.org/Service.owl#> .
                        <http://clement.concept.org/#request_light> a pvn:ServiceRequest ;
                          pvn:requiredResult [
                            a ns:Result ;
                            ns:hasEffect (
                              [
                                :affectedProperty [
                                  a :PropertyPath ;
                                  :thePath (
                                    ns1:hasValue
                                  )
                                ] ;
                                a :ChangeEffect ;
                                :propertyValue "0"^^xsd:int
                              ]
                            )
                          ] ;
                          pvn:requestedService [
                            a <http://ontology.universaal.org/PhThing.owl#DeviceService> ;
                            pvn:instanceLevelRestrictions (
                              [
                                owl:hasValue "&Allume;0&Allume;"^^xsd:int ;
                                a owl:Restriction ;
                                owl:onProperty ns1:hasValue
                              ]
                            ) ;
                            pvn:numberOfValueRestrictions "1"^^xsd:int
                          ] .

                    ]]>
                </serialization>
            </requirement>
```

**Comment by Alfiva** [comment] 2017-06-21 15:25
I think the problem is you are trying to mix two different concepts. You cannot have both addValueFilter and addChangeEffect over the same property in this case.
Setting .addChangeEffect(new String[]{LightActuator.PROP_HAS_VALUE }, new Integer(0)); means this request is for **setting PROP_HAS_VALUE to 0**. It will only match to a profile that has set .addChangeEffect(new String[]{LightActuator.PROP_HAS_VALUE }, new Integer(0));
So, as you describe, if you change that 0 from the request to 100 using Android variables, there will no longer be any match. Regardless of .addValueFilter or .addFilteringInput.
If what you want to do is something like a method that does "set value to X", then you must **only** use the .addValueFilter in the request and .addFilteringInput in the profile.
Then in Android, you can change the initial value in the serialization to any value you want using intent extras and variables, as explained before. And you can get that value in the other end, also using extras and variables (only they work differently, the other way around).

**Comment by ClementBrohon** [comment] 2017-06-22 11:04
It solved part of my problem, I can now receive calls for all the intensities, but I still can not get this value.

> And you can get that value in the other end, also using extras and variables (only they work differently, the other way around).

I don't know how.

![image](https://user-images.githubusercontent.com/25262825/27430400-b8467940-5748-11e7-99dd-6c457e323384.png)

```
public void onReceive(Context context, Intent intent) {
        nbrequete ++;
        messageTest = nbrequete.toString();
        Bundle bundle = intent.getExtras();
        if (bundle != null) {
            for (String key : bundle.keySet()) {
                Object value = bundle.get(key);
                messageTest = messageTest + "\n key  :  " + key + " \n  message:  " + value.toString() ;
            }
        }
}
```

My intent haven't my extra var1. I don't know why but I'm sure he did not get to my method. It's not as obvious to me as the tutorial seems to say.

> The <key> tag must contain the fully qualified (namespace included) URI of the input you want to map, as it appears in the serialization. The <value> tag is the name of the intent extra where the value of that input will be stored.

```
                <input>
                    <key>var1</key>
                    <value>Lamps</value>
                </input>
```


Could you explain how set up my xml for having my extra in my intent please?

the last version of my code;

```
<title>Turn light on</title>
                <description>SERVICE CALLEE PROFILE: Turn on a specific light source.</description>
                <action>org.universaal.nativeandroid.lightbluetooth.PUT_ON</action>
                <category>android.intent.category.DEFAULT</category>
                <input>
                    <key>var1</key>
                    <value>Lamps</value>
                </input>
                <serialization>
                    <![CDATA[
                        @prefix ns: <http://clement.concept.org#> .
                        @prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .
                        @prefix owl: <http://www.w3.org/2002/07/owl#> .
                        @prefix ns1: <http://www.daml.org/services/owl-s/1.1/Profile.owl#> .
                        @prefix ns2: <http://www.daml.org/services/owl-s/1.1/Service.owl#> .
                        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
                        @prefix ns3: <http://clement.concept.org/#> .
                        @prefix : <http://www.daml.org/services/owl-s/1.1/Process.owl#> .
                        ns:Profile ns2:presentedBy ns3:device_service_watch_light_change ;
                          a ns1:Profile ;
                          ns1:has_process ns3:device_service_watch_light_changeProcess ;
                          ns1:hasInput (
                            ns:var1
                          ) .
                        ns:var1 <http://ontology.universAAL.org/Service.owl#parameterCardinality> "1"^^xsd:int ;
                          a :Input ;
                          :parameterType "http://www.w3.org/2001/XMLSchema#int"^^xsd:anyURI .
                        :ThisPerform a :Perform .
                        ns3:device_service_watch_light_change a <http://ontology.universaal.org/PhThing.owl#DeviceService> ;
                          pvn:instanceLevelRestrictions (
                            [
                              owl:hasValue [
                                :fromProcess :ThisPerform ;
                                a :ValueOf ;
                                :theVar ns:var1
                              ] ;
                              a owl:Restriction ;
                              owl:onProperty <http://ontology.universAAL.org/Device.owl#hasValue>
                            ]
                          ) ;
                          ns2:presents ns:Profile ;
                          pvn:numberOfValueRestrictions "1"^^xsd:int .

                    ]]>
                </serialization>
```

**Comment by Alfiva** [comment] 2017-06-22 11:10
```
...
                <input>
                    <key>http://clement.concept.org#var1</key>
                    <value>Lamps</value>
                </input>
...
```

**Comment by ClementBrohon** [comment] 2017-06-22 13:11
:) Thank you

**Comment by Alfiva** [comment] 2017-08-02 11:35
No further activity, closing.

**Closed as completed by Alfiva** 2017-08-02 11:35 UTC
Labels: help wanted
